"""intial relationships

Revision ID: 64b641c2fce9
Revises: 
Create Date: 2024-03-06 00:16:31.820814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b641c2fce9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_medias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_medias')),
    sa.UniqueConstraint('url', name=op.f('uq_journal_medias_url'))
    )
    op.create_table('journal_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_journal_tags_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_journal_entries_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_entries'))
    )
    op.create_table('entry_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('JournalEntry', sa.Integer(), nullable=True),
    sa.Column('JournalTag', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['JournalEntry'], ['journal_entries.id'], name=op.f('fk_entry_tags_JournalEntry_journal_entries')),
    sa.ForeignKeyConstraint(['JournalTag'], ['journal_tags.id'], name=op.f('fk_entry_tags_JournalTag_journal_tags')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entry_tags'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry_tags')
    op.drop_table('journal_entries')
    op.drop_table('users')
    op.drop_table('journal_tags')
    op.drop_table('journal_medias')
    # ### end Alembic commands ###
